version: '3.9'

# Dev
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

# volumes:
#   static:

networks:
  default_network:
    name: default_network
    driver: bridge