@ChessAPI_HostAddress = http://localhost:5000

### Get Weather Forecast (example)
GET {{ChessAPI_HostAddress}}/weatherforecast
Accept: application/json

### Get Legal Moves
GET {{ChessAPI_HostAddress}}/api/chess/legalmoves?fen=YOUR_FEN_STRING
Accept: application/json

### Get Bot Move
GET {{ChessAPI_HostAddress}}/api/chess/bot?fen=YOUR_FEN_STRING
Accept: application/json